name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build site
      run: npm run build  # Ensure this outputs to dist/

    - name: Deploy dist/ to remote server
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: dist/
        remote_path: /var/www/html/
        remote_host: 143.198.111.133
        remote_user: gmsteck
        remote_key: ${{ secrets.PRIVATE_KEY }}

    - name: Reload NGINX on remote server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa gmsteck@143.198.111.133 "sudo -n systemctl reload nginx"
