name: CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Deploy using rsync to server
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        # -v: verbose
        # -z: compress files during transfer
        # -r: copy files recursively
        # --delete: delete extraneous files from dest dirs
        switches: -vzr --delete
        path: gmsteck.com/
        remote_path: /var/www/html/
        remote_host: 143.198.111.133
        remote_user: gmsteck
        remote_key: ${{ secrets.PRIVATE_KEY }}
